### ISSUE TITLE
Customize preferences file name

### ISSUE THREAD

**Issue by mastrgamr** [GrenderG/Prefs#2]
I [notice](https://github.com/GrenderG/Prefs/blob/master/lib/src/main/java/es/dmoral/prefs/Prefs.java#L20) by default this library handles preferences with the name 'preferences' but I think it would be cool to specify the name of the Shared Preference file the user wants to access.

Basically creating a call like:
`Prefs.with(yourContext, "FILE NAME").readInt(YOUR_KEY_VALUE);` having the second parameter optional, defaulting to the what the library does now.

**Comment by GrenderG** [comment]
That's a good idea, maybe I'll think a way to customize that parameter and other things. Thanks!

**Comment by GrenderG** [comment]
Sorry for the long delay, the library has been updated with that option.
